## Simple *numpy* exercise


I am sure that you were already familiar with all the concepts presented above, but a short recap is always welcomed.


Now let's do a very simple exercise with *numpy* arrays.


In a (4, 7) *numpy* array we store data about the calorie intake and expenditure of a person throughout the week, as follows:
- The rows specify the number of calories from protein sources, the number of calories from fat sources, the number of calories from carbohydrates sources and the calorie expenditure through physical activity, respectively.
- The columns specify the day of the week for which the data were recorded.
   
Compute the following (without using any explicit for loop):
- the total number of calories consumed each day;
- the percentage of calories from protein sources and the percentage of calories from carbohydrates (as an array with 2 rows and 7 columns), rounded to two decimal places [numpy.around](https://numpy.org/doc/stable/reference/generated/numpy.around.html) );
- the day in which the maximum number of calories were burned through physical activity;
- the sum of calorie expenditure and calories from protein sources for each working day (the result with be an array with 5 elements);
- the number of calories from protein sources, number of calories from fat sources, number of calories from carbohydrate sources and the calorie expenditure for the week as a (1, 4) array.


In [49]:
import numpy as np

# find a is what percent of b
def percentage(a,b):
    return a/b*100

days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
statistics = np.array([
                      [90, 100, 170, 200, 98, 167, 150], # calories from protein
                      [300, 200, 150, 174, 200, 270, 240], # calories from fat
                      [340, 255, 400, 500, 301, 200, 300],  # calories from carbs
                      [250, 90, 170, 200, 87, 160, 200]]) # calorie expenditure

## YOUR CODE HERE

calories_per_day = np.sum(statistics, axis=0)
print("calories_per_day")
print(calories_per_day, "\n")

protein_and_carbs = np.array([np.around(percentage(calories_per_day, statistics[0]),2),np.around(percentage(calories_per_day,statistics[2]),2)])
print("percentage of calories from protein and carbs")
print(protein_and_carbs, "\n")


max_calories_burned = np.max(statistics[3])
print("max calories burned")
print(max_calories_burned, "\n")

expenditure_and_protein_sum = np.sum(statistics[0:2,:5], axis=0)
print("expenditure and protein sum")
print(expenditure_and_protein_sum, "\n")

sum_of_all_calories = np.sum(statistics, axis=1)
print("sum of all calories")    
print(sum_of_all_calories, "\n")
## END YOUR CODE



calories_per_day
[ 980  645  890 1074  686  797  890] 

calories_per_week
[ 975 1534 2296 1157] 

percentage of calories from protein and carbs
[[1088.89  645.    523.53  537.    700.    477.25  593.33]
 [ 288.24  252.94  222.5   214.8   227.91  398.5   296.67]] 

max calories burned
250 

expenditure and protein sum
[390 300 320 374 298] 

sum of all calories
[ 975 1534 2296 1157] 

